#
# Execute command to start mysql and rails:
#       docker-compose up
#
# To create database
#       docker-compose run web rake db:setup
#
version: '3'
services:
  web:
    image: ploh/rtbadmin_open
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    environment:
      - RTB4FREE_CUSTOMER_NAME=RTB4FREE
      - RTB4FREE_DATABASE_HOST=db
      - RTB4FREE_DATABASE_PORT=3306
      - RTB4FREE_DATABASE_USERNAME=ben
      - RTB4FREE_DATABASE_PASSWORD=test
      - RTB4FREE_DATABASE_NAME=rtb4free
      - RTB4FREE_ELASTICSEARCH_REPORTS_ENABLE=false
      - RTB4FREE_ELASTICSEARCH_HOST=
      - RTB4FREE_ELASTICSEARCH_KIBANA_HOST=
      - RTB4FREE_ELASTICSEARCH_KIBANA_PORT=
      - RTB4FREE_ELASTICSEARCH_KIBANA_URL=
      - RTB4FREE_ELASTICSEARCH_REQUESTS_INDEX=bidderlogs
      - RTB4FREE_ELASTICSEARCH_STATS_INDEX=stats
    networks:
      - rtb_net
      
networks:
  rtb_net:
    external: true      